### ISSUE TITLE
Wrong day of the week

### ISSUE THREAD

**Issue by barr-code** [shekibobo/xdan-datetimepicker-rails#1]
This really is a fantastic gem, but something strange is happening. We have a datetime range picker in our app, and for almost everyone, it's being generated properly. However, we have just had one user in Australia report that the days of the week are off by 1 day. It's not a leap year problem, February the 29th is being generated in the calendar. It's just on a Tuesday instead of a Monday.

What might be causing the difference for that user? Are there local browser or computer settings which would interfere with the DataTime calculation? Where does the datetimepicker get its date information from for each user? Is there anything we can do to make sure that the calendar is generated properly for everyone? 

Thanks.

**Comment by shekibobo** [comment]
What settings to you have implemented? I've just [updated this gem](https://github.com/shekibobo/xdan-datetimepicker-rails/compare/2.4.3...2.5.1) to use the latest version of the [the datetimepicker](https://github.com/xdan/datetimepicker), so you may want to try updating and see if the issue was fixed. I don't actually maintain the source code of the datepicker, just the gem to include it via assets. I'd have to refer you to the documentation for the javascript library.

**Comment by shekibobo** [comment]
Closing as stale. If you are still having issues, please reopen. Thanks.
